<?php
declare(strict_types=1);
session_start(); require_once "../config/database.php";
header("Content-Type: application/json; charset=UTF-8"); header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
function jr(bool $ok,string $msg,array $x=[],int $c=200): never { http_response_code($c); echo json_encode(array_merge(["status"=>$ok,"pesan"=>$msg],$x),JSON_UNESCAPED_UNICODE); exit; }
if($_SERVER["REQUEST_METHOD"]!=="POST") jr(false,"Metode tidak diizinkan.",[],405); if(!isset($_SESSION["siswa_id"])) jr(false,"Sesi login siswa tidak ditemukan.",[],401);
$siswa=(int)$_SESSION["siswa_id"]; $raw=file_get_contents("php://input"); $d=json_decode($raw,true); if(!is_array($d)) $d=$_POST; if(!is_array($d)) jr(false,"Data request tidak valid.",[],400);
$sid=(int)($d["sesi_id"]??0); $uid=(int)($d["ujian_id"]??0); $jenis=trim((string)($d["jenis"]??"")); if($sid<=0||$uid<=0||$jenis==="") jr(false,"Data pelanggaran tidak lengkap.",[],400);
$allowed=["Pindah tab","Halaman ditinggalkan","Browser diminimalkan","Keluar fullscreen"]; if(!in_array($jenis,$allowed,true)) jr(false,"Jenis pelanggaran tidak valid.",[],400);
$conn->begin_transaction(); try {
$st=$conn->prepare("SELECT su.id,su.siswa_id,su.ujian_id,su.status,su.batas_waktu,u.maks_pelanggaran FROM sesi_ujian su INNER JOIN ujian u ON u.id=su.ujian_id WHERE su.id=? AND su.siswa_id=? AND su.ujian_id=? LIMIT 1 FOR UPDATE"); if(!$st) throw new Exception("Gagal memeriksa sesi."); $st->bind_param("iii",$sid,$siswa,$uid); $st->execute(); $s=$st->get_result()->fetch_assoc(); $st->close(); if(!$s) throw new Exception("Sesi ujian tidak valid."); if($s["status"]!=="mengerjakan") throw new Exception("Ujian sudah selesai."); if(strtotime($s["batas_waktu"])<=time()) throw new Exception("Waktu ujian telah habis.");
$max=(int)$s["maks_pelanggaran"]; $st=$conn->prepare("SELECT COUNT(*) total FROM pelanggaran_ujian WHERE sesi_id=?"); if(!$st) throw new Exception("Gagal menghitung pelanggaran."); $st->bind_param("i",$sid); $st->execute(); $before=(int)$st->get_result()->fetch_assoc()["total"]; $st->close();
if($max>0&&$before>=$max){$conn->commit();jr(false,"Batas maksimal pelanggaran sudah tercapai.",["auto_submit"=>true,"total_pelanggaran"=>$before,"maks_pelanggaran"=>$max],409);}
$st=$conn->prepare("INSERT INTO pelanggaran_ujian(sesi_id,siswa_id,ujian_id,jenis) VALUES(?,?,?,?)"); if(!$st) throw new Exception("Gagal menyiapkan pencatatan pelanggaran."); $st->bind_param("iiis",$sid,$siswa,$uid,$jenis); if(!$st->execute()) throw new Exception("Gagal menyimpan pelanggaran."); $st->close(); $total=$before+1;
if($max<=0||$total<$max){$conn->commit();jr(true,"Pelanggaran berhasil dicatat.",["auto_submit"=>false,"total_pelanggaran"=>$total,"maks_pelanggaran"=>$max]);}
$st=$conn->prepare("SELECT COUNT(*) total FROM soal WHERE ujian_id=?"); if(!$st) throw new Exception("Gagal menghitung soal."); $st->bind_param("i",$uid); $st->execute(); $jumlah_soal=(int)$st->get_result()->fetch_assoc()["total"]; $st->close();
$st=$conn->prepare("SELECT COUNT(*) total FROM jawaban WHERE sesi_id=?"); if(!$st) throw new Exception("Gagal menghitung jawaban."); $st->bind_param("i",$sid); $st->execute(); $dijawab=(int)$st->get_result()->fetch_assoc()["total"]; $st->close();
$st=$conn->prepare("SELECT COUNT(*) total FROM jawaban j INNER JOIN opsi_soal o ON j.opsi_id=o.id WHERE j.sesi_id=? AND o.benar=1"); if(!$st) throw new Exception("Gagal menghitung nilai."); $st->bind_param("i",$sid); $st->execute(); $benar=(int)$st->get_result()->fetch_assoc()["total"]; $st->close(); $salah=max(0,$dijawab-$benar); $nilai=$jumlah_soal>0?($benar/$jumlah_soal)*100:0;
$st=$conn->prepare("SELECT id FROM hasil_ujian WHERE sesi_id=? LIMIT 1"); if(!$st) throw new Exception("Gagal memeriksa hasil ujian."); $st->bind_param("i",$sid); $st->execute(); $old=$st->get_result()->fetch_assoc(); $st->close();
if($old){$hasil=(int)$old["id"];}else{$st=$conn->prepare("INSERT INTO hasil_ujian(sesi_id,siswa_id,ujian_id,jumlah_soal,jumlah_dijawab,jumlah_benar,jumlah_salah,nilai) VALUES(?,?,?,?,?,?,?,?)"); if(!$st) throw new Exception("Gagal menyiapkan hasil ujian."); $st->bind_param("iiiiiiid",$sid,$siswa,$uid,$jumlah_soal,$dijawab,$benar,$salah,$nilai); if(!$st->execute()) throw new Exception("Gagal menyimpan hasil ujian."); $hasil=$conn->insert_id; $st->close();}
$st=$conn->prepare("UPDATE sesi_ujian SET status='selesai',selesai=NOW(),terkunci_pengawas=0 WHERE id=? AND siswa_id=? AND ujian_id=? AND status='mengerjakan'"); if(!$st) throw new Exception("Gagal menyelesaikan sesi ujian."); $st->bind_param("iii",$sid,$siswa,$uid); if(!$st->execute()||$st->affected_rows!==1) throw new Exception("Sesi ujian gagal diselesaikan."); $st->close(); $st=$conn->prepare("UPDATE kode_pengawas_ujian SET status='batal' WHERE sesi_id=? AND status='aktif'"); if($st){$st->bind_param("i",$sid);$st->execute();$st->close();}
$conn->commit(); jr(true,"Batas maksimal pelanggaran tercapai. Ujian dikirim otomatis.",["auto_submit"=>true,"total_pelanggaran"=>$total,"maks_pelanggaran"=>$max,"hasil_id"=>$hasil,"jumlah_soal"=>$jumlah_soal,"jumlah_dijawab"=>$dijawab,"jumlah_benar"=>$benar,"jumlah_salah"=>$salah,"nilai"=>$nilai]);
} catch(Throwable $e){$conn->rollback();error_log("catat-pelanggaran.php: ".$e->getMessage());jr(false,$e->getMessage(),["auto_submit"=>false],400);}
?>
